name: continuous integration

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Using Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover -s . -p "teste_*.py"

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # 1️⃣ Baixar código novamente
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Fazer login no Docker Hub (se quiser publicar imagem)
      - name: Log in to Docker Hub
        if: secrets.DOCKER_USERNAME != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build da imagem Docker
      - name: Build Docker image
        run: docker build -t my-flask-api:latest .

      # 4️⃣ (Opcional) Push para o Docker Hub
      - name: Push Docker image
        if: secrets.DOCKER_USERNAME != ''
        run: docker push my-flask-api:latest
